### PR TITLE
A Bernie Bootstrap <h1>

### PR DESCRIPTION
**Pull request by eric-johnson**
Begins SandersForPresident/BusRSVP#2.
Created a page so I can see that the styles actually apply.
Copy/pasted bootstrap js & css into lib/assets.
It looks like these styles are updated frequently, so I'm considering
making a rake task to pull down the latest.

### CODE REVIEW

**Comment by bryceroney** [comment]
Instead shouldn't we make bernstrap a proper bower package so that it can be linked as a rails-assets gem?

**Comment by eric-johnson** [comment]
Probably...  I didn't think of that
I'll take another stab at it.

**Comment by bryceroney** [comment]
I've tried to do that here: https://github.com/SandersForPresident/bootstrap/pull/2

**Comment by maclover7** [comment]
Looks nice so far, @eric-johnson! Two quick things: (1) Can you move the assets to vendor/assets? That's typically where vendored (external) stylesheets live. (2) Can you combine both of the Rake tasks into a single file, and then stick them under the same namespace? They can live in lib/tasks/berniestrap.rake, and then just stick the tasks under the :berniestrap namespace. Thanks for submitting this PR!

**Comment by ajwhite** [comment]
Please use `bower` here and avoid checking in the assets

**Comment by maclover7** [comment]
Maybe we can use the rails-assets bower-rubygem crossover service?

**Comment by eric-johnson** [comment]
That thought crossed my mind, but Berniestrap isn't up on bower.io (yet?).

**Comment by ajwhite** [comment]
Why not just use bower? /cc @schneidmaster who just incorporated this in another project.

**Comment by maclover7** [comment]
Please resolve merge conflicts.

**Comment by eric-johnson** [comment]
I'm planning on throwing this away and replacing it with this in the Gemfile:

    source 'https://rails-assets.org' do
      gem 'rails-assets-berniestrap'
    end

**Pull request closed without merging**
