### PR TITLE
Upgraded Ruby and Rails; Locked down rspec-rails gem; Add LICENSE.txt file

### PR DESCRIPTION
**Pull request by jasnow**
* Upgraded Ruby to 2.3.0.
 * Upgraded Rails to 4.2.6.
 * Locked down rspec-rails gem to prevent broken build.
 * Added LICENSE.txt file (used same file as BernieBNB project).

### CODE REVIEW

**Comment by ajwhite** [comment]
If @maclover7, @eric-johnson, or @kris-luminar could confirm the Ruby changes, this should be good.

If you'd like to remove the license file and contribute that separately, i can merge that. Otherwise we'll hang tight until a reviewer can step in here

**Comment by jasnow** [comment]
I will check tomorrow AM and fix it based on feedback.

**Comment by ajwhite** [comment]
Sounds good, @jasnow.

I'm sure this is all fine and good to go, I'm just not a maintainer of this specific project so I can't verify for ya!

**Comment by jasnow** [comment]
I always want someone to review my work before merging.

**Comment by ajwhite** [comment]
:100:

**Comment by kris-luminar** [comment]
+1

**Pull request merged**
