### PR TITLE
adds ruby version to Gemfile

### PR DESCRIPTION
**Pull request by kris-luminar**
* This way, the Ruby VM on your deployment/CI server will match your local one.

### CODE REVIEW

**Comment by maclover7** [comment]
Thanks for this PR! I believe we are having the default Ruby version for this project be 2.2.3 though, not 2.2.2.

**Comment by kris-luminar** [comment]
@maclover7 please check latest work.

**Comment by kris-luminar** [comment]
I had to update the travis.yml file to get the tests to pass on Travis.

**Comment by maclover7** [comment]
Awesome -- thank you for this PR!

**Pull request merged**
