### PR TITLE
Initial Facebook Omniauth implementation

### PR DESCRIPTION
**Pull request by maclover7**
#8

### CODE REVIEW

**Comment by eric-johnson** [comment]
I checked this out and got it working. looks good! I had to dig around to find out how to set everything up on the Facebook side. We'll definitely need to add something to the contributor guide for this.

We'll need to create a [Facebook app](https://developers.facebook.com/apps) if you haven't made one already. I'm not sure if we need to made test apps on top of that for developers to use, or if having devs create their own facebook apps and going through the steps will continue to suffice.

**Comment by maclover7** [comment]
Yep, I have a test app setup on my Facebook account, and I'm using that for local testing. Will add a line to the contributor guide about setting up a test app.

**Comment by eric-johnson** [comment]
Can we merge this in? I'd like to start building on top of it.

**Comment by maclover7** [comment]
:+1:

**Pull request merged**
