### PR TITLE
Ignore vendor/bundle so I can install gems locally.

### PR DESCRIPTION
**Pull request by eric-johnson**
Unless we actually want to check in gems.

### CODE REVIEW

**Comment by maclover7** [comment]
Why do we need to ignore vendor/bundle - what are you putting in there? When you run `bundle install`, I don't think vendor/bundle is used at all.

**Comment by eric-johnson** [comment]
Not a big deal, I just prefer to install gems local to the project to keep things separated.
`bundle install --path vendor/bundle`

**Comment by ajwhite** [comment]
Should update the docs if we're designating `vendor/bundle` as the local installation path

**Comment by eric-johnson** [comment]
That's fine, but I don't think designating a directory to install your gems is necessary. You can install your gems pretty much anywhere on your computer, as long as your .bundle/config knows where to look.

**Comment by ajwhite** [comment]
Well i mean, we're adding it to the `gitignore`, so we ought to describe that, no?

**Comment by ajwhite** [comment]
Just seems like if people have a preference to local installs that we should standardize that to the directory you've chosen here

**Comment by eric-johnson** [comment]
For people that choose to install their gems local to the project they're working on, `vendor/bundle` is the conventional place for them to install those gems.

**Comment by ajwhite** [comment]
Oh, already standardized, great!

**Comment by ajwhite** [comment]
(not a rubyist here, apologies)

**Comment by maclover7** [comment]
The default for Ruby projects (for the 99% of devs I have worked with) is to just run `bundle install`, not to install to vendor/bundle. If you choose to download your gems there, it's cool with me. I'd like it if the project followed Ruby community "standards". Sorry if this is coming off as harsh at all.

**Pull request closed without merging**
